import os
import re
import json
import joblib
import asyncio
import pandas as pd
import numpy as np
import httpx
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from sklearn.metrics.pairwise import cosine_similarity

app = FastAPI(title="Pet Vet AI — Semantic Gateway", version="5.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

_HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR = os.path.join(_HERE, "assets")

# ── Load all assets at startup ───────────────────────────────────────────────
model = joblib.load(os.path.join(ASSETS_DIR, "model.joblib"))

# Semantic embedding assets (generated by local_embedding_pretrain.py)
_sym_embeddings = joblib.load(os.path.join(ASSETS_DIR, "symptom_embeddings.joblib"))  # (N, 384)
_sym_labels     = joblib.load(os.path.join(ASSETS_DIR, "symptom_labels.joblib"))      # list[str]

# Ensure float32 numpy array for fast cosine math
_sym_embeddings = np.array(_sym_embeddings, dtype=np.float32)

with open(os.path.join(ASSETS_DIR, "encoders.json"))    as f: encoders     = json.load(f)
with open(os.path.join(ASSETS_DIR, "disease_info.json")) as f: disease_info = json.load(f)

# ── Hugging Face Inference API setup ─────────────────────────────────────────
_HF_TOKEN  = os.getenv("HF_TOKEN", "")
_HF_MODEL  = "sentence-transformers/all-MiniLM-L6-v2"
_HF_URL    = f"https://api-inference.huggingface.co/pipeline/feature-extraction/{_HF_MODEL}"
_HF_HEADERS = {"Authorization": f"Bearer {_HF_TOKEN}"} if _HF_TOKEN else {}

# Minimum cosine similarity score to accept a semantic symptom match
_SEM_THRESHOLD = 0.55

master_symptoms = encoders["symptoms"]
SYNONYM_RULES: dict = encoders.get("synonym_rules", {})

# Pre-compute a set for O(1) membership checks
_master_sym_set: set = set(master_symptoms)


# ── Vitals reference ranges per species (temp °C, hr bpm) ────────────────────
VITALS_RANGES = {
    "Dog":    {"temp": (37.5, 39.5), "hr": (60, 180)},
    "Cat":    {"temp": (38.0, 39.5), "hr": (120, 240)},
    "Rabbit": {"temp": (38.5, 40.0), "hr": (120, 325)},
    "Horse":  {"temp": (37.0, 38.5), "hr": (28, 44)},
    "Cow":    {"temp": (38.0, 39.5), "hr": (40, 80)},
    "Sheep":  {"temp": (38.5, 40.0), "hr": (60, 120)},
    "Goat":   {"temp": (38.5, 40.0), "hr": (60, 120)},
    "Pig":    {"temp": (38.0, 40.0), "hr": (55, 100)},
    "Ferret": {"temp": (37.8, 40.0), "hr": (180, 250)},
}

# Absolute impossible limits (physics-based sanity checks)
TEMP_ABSOLUTE_MIN = 25.0   # below 25°C means instrument error or dead animal
TEMP_ABSOLUTE_MAX = 45.0   # above 45°C is incompatible with life
HR_ABSOLUTE_MIN   = 10     # below 10 bpm is not a living animal
HR_ABSOLUTE_MAX   = 500    # above 500 bpm is instrument error


# ── Species-Disease Compatibility Map ─────────────────────────────────────────
# Strict species prefixes: a disease named with these prefixes ONLY belongs to
# that species. Diseases without a species prefix are considered general and
# allowed for all species.
_SPECIES_PREFIXES: dict = {
    "Dog":    ["canine"],
    "Cat":    ["feline"],
    "Cow":    ["bovine"],
    "Horse":  ["equine"],
    "Pig":    ["porcine", "swine", "african swine"],
    "Goat":   ["caprine", "goat"],
    "Sheep":  ["ovine", "sheep", "scrapie", "maedi", "caseous"],
    "Rabbit": ["rabbit", "myxomatosis", "snuffles"],
    "Ferret": [],
}

# Additional explicit overrides for diseases that don't have a prefix but are
# still species-specific (sourced from training-data inspection).
_DISEASE_SPECIES_OVERRIDES: dict = {
    "Mastitis":                      {"Cow", "Goat", "Sheep"},
    "Laminitis":                     {"Horse", "Goat", "Cow"},
    "Equine Laminitis":              {"Horse"},
    "Gastrointestinal Stasis":       {"Rabbit"},
    "Bluetongue":                    {"Sheep", "Goat", "Cow"},
    "Kennel Cough":                  {"Dog"},
    "Bordetella Infection":          {"Dog", "Cat", "Rabbit"},
    "Heartworm Disease":             {"Dog"},
    "Distemper":                     {"Dog"},
    "Foot and Mouth Disease":        {"Cow", "Sheep", "Goat", "Pig"},
    "Footrot":                       {"Sheep", "Goat", "Cow"},
    "Chlamydia in Sheep":            {"Sheep"},
    "Contagious Ecthyma":            {"Sheep", "Goat"},
    "Contagious Abortion":           {"Goat", "Sheep", "Cow"},
    "Actinobacillus Pleuropneumonia":{"Pig"},
    "Actinobacillus Suis":           {"Pig"},
    "African Swine Fever":           {"Pig"},
    "Hyperthyroidism":               {"Cat", "Dog"},
    "Snuffles":                      {"Rabbit"},
    "Rabbit Syphilis":               {"Rabbit"},
    "Rabbit Hemorrhagic Disease":    {"Rabbit"},
    "Myxomatosis":                   {"Rabbit"},
    "Cryptosporidiosis":             {"Cow", "Sheep", "Goat"},
}

# General diseases (permitted for any species) — these are diseases from the
# 5-category NLP corpus that don't have a species prefix.
_GENERAL_DISEASES = {
    "Healthy / No Disease", "Digestive Issues", "Lameness", "Skin Lesions",
    "Ear Infections", "Parasites", "Gastroenteritis", "Gastrointestinal Infection",
    "Arthritis", "Conjunctivitis", "Respiratory Infection",
    "Upper Respiratory Infection", "Degenerative Joint Disease",
    "Chronic Bronchitis", "Allergic Rhinitis", "Fungal Infection",
    "Pneumonia", "Coccidiosis", "Inflammatory Bowel Disease",
    "Leptospirosis", "Giardiasis", "Intestinal Parasites", "Enteritis",
    "Salmonellosis", "Pasteurellosis", "Weight Loss", "Pregnancy",
    "Distemper", "Parvovirus", "Lyme Disease",
}


def _is_disease_allowed_for_species(disease_name: str, species: str) -> bool:
    """
    Returns True if disease_name is biologically possible for the given species.
    Logic:
      1. If explicitly in _DISEASE_SPECIES_OVERRIDES, check the allowed set.
      2. If disease name starts with a strict species prefix for a DIFFERENT species → block.
      3. Otherwise (no prefix / general disease) → allow.
    """
    # Step 1: explicit override wins
    if disease_name in _DISEASE_SPECIES_OVERRIDES:
        return species in _DISEASE_SPECIES_OVERRIDES[disease_name]

    # Step 2: check strict prefix ownership
    d_lower = disease_name.lower()
    for sp, prefixes in _SPECIES_PREFIXES.items():
        for prefix in prefixes:
            if d_lower.startswith(prefix):
                # This disease belongs to `sp`
                return sp == species

    # Step 3: general / no species prefix → allow for all
    return True


def _vitals_are_abnormal(species: str, temperature: Optional[float], heart_rate: Optional[float]) -> bool:
    """Returns True if either vital is outside the species-normal range."""
    v = VITALS_RANGES.get(species, {})
    if temperature is not None and "temp" in v:
        lo, hi = v["temp"]
        if temperature < lo or temperature > hi:
            return True
    if heart_rate is not None and "hr" in v:
        lo, hi = v["hr"]
        if heart_rate < lo or heart_rate > hi:
            return True
    return False


# ── Disease alias map: encoder name -> disease_info.json key ─────────────────
# Bridges the short encoder names to the verbose info-file keys.
DISEASE_ALIAS: dict = {
    "Arthritis":                          "Arthritis and Joint Pain (cats and Dogs)",
    "Bovine Mastitis":                    "Mastitis",
    "Bovine Respiratory Disease":         "Bovine Respiratory Disease (brd, \u2018shipping Fever\u2019)",
    "Bovine Respiratory Disease Complex": "Bovine Respiratory Disease (brd, \u2018shipping Fever\u2019)",
    "Bovine Respiratory Syncytial Virus": "Bovine Respiratory Disease (brd, \u2018shipping Fever\u2019)",
    "Bovine Viral Diarrhea":              "Bovine Viral Diarrhoea Virus (pestivirus)",
    "Canine Leptospirosis":               "Leptospirosis",
    "Canine Parvovirus":                  "Parvovirus",
    "Coccidiosis":                        "Coccidiosis (rabbit)",
    "Bovine Coccidiosis":                 "Coccidiosis (black Scours)",
    "Distemper":                          "Canine Distemper",
    "Equine Leptospirosis":               "Leptospirosis",
    "Goat Pox":                           "Sheep and Goat Pox (sgp)",
    "Myxomatosis":                        "Myxomatosis (rabbit)",
    "Parasites":                          "Ascaris",
    "Pasteurellosis":                     "Pasteurellosis (rabbit)",
    "Degenerative Joint Disease":         "Arthritis and Joint Pain (cats and Dogs)",
    # Equine Arthritis has its own species-specific INLINE_INFO — do not alias to cats/dogs
    "Ear Infections":                     "Ear Problems (cats and Dogs)",
    "Feline Respiratory Disease Complex": "Cat Flu",
    "Feline Herpesvirus":                 "Cat Flu",
    "Feline Calicivirus":                 "Cat Flu",
    "Feline Rhinotracheitis":             "Cat Flu",
    "Feline Viral Rhinotracheitis":       "Cat Flu",
    "Feline Upper Respiratory Infection": "Cat Flu",
    "Feline Respiratory Infection":       "Cat Flu",
    "Upper Respiratory Infection":        "Cat Flu",
    "Respiratory Infection":              "Cat Flu",
    "Canine Flu":                         "Canine Influenza",
    "Canine Cough":                       "Kennel Cough",
    "Bovine Influenza":                   "Bovine Rhinotracheitis",
    "Bovine Parainfluenza":               "Bovine Rhinotracheitis",
    "Bovine Tuberculosis":                "Tuberculosis (cattle)",
    "Tuberculosis":                       "Tuberculosis (cattle)",
    "Intestinal Parasites":               "Ascaris",
    "Feline Renal Disease":               "Kidney Disease (cats and Dogs)",
    "Heartworm Disease":                  "Canine Heartworm Disease",
    "Feline Leukemia":                    "Feline Leukemia Virus",
    "Panleukopenia":                      "Feline Panleukopenia",
    "Feline Panleukopenia Virus":         "Feline Panleukopenia",
    "Salmonellosis":                      "Salmonellosis=paratyphus",
    "Gastrointestinal Infection":         "Gastrointestinal and Digestive Disorders (cats and Dogs)",
    "Gastroenteritis":                    "Gastrointestinal and Digestive Disorders (cats and Dogs)",
    "Gastrointestinal Stasis":            "Gastrointestinal and Digestive Disorders (cats and Dogs)",
    "Inflammatory Bowel Disease":         "Gastrointestinal and Digestive Disorders (cats and Dogs)",
    "Digestive Issues":                   "Gastrointestinal and Digestive Disorders (cats and Dogs)",
    "Feline Infectious Peritonitis":      "Gastrointestinal and Digestive Disorders (cats and Dogs)",
    "Skin Lesions":                       "Dermatitis (cats and Dogs)",
    "Conjunctivitis":                     "Eye Inflammation (cats and Dogs)",
    "Respiratory Syncytial Virus":        "Bovine Respiratory Disease (brd, \u2018shipping Fever\u2019)",
    # Caprine/Porcine respiratory diseases use their own INLINE_INFO entries (not bovine)
    "Lyme Disease":                       "Tick Borne Disease",
    "Equine Lyme Disease":                "Tick Borne Disease",
    "Lameness":                           "Arthritis and Joint Pain (cats and Dogs)",
    "Laminitis":                          "Equine Laminitis",
    # Pneumonia has species-appropriate INLINE_INFO entries — do not alias to bovine
    "Bovine Pneumonia":                   "Pnuemonia (cattle)",
    # Feline Asthma and Chronic Bronchitis have correct INLINE_INFO — do not alias to canine flu
    "Feline Chlamydia":                   "Feline Chlamydia",
    # Rabbit diseases each have distinct INLINE_INFO — do not collapse them all into Myxomatosis
    "Snuffles":                           "Pasteurellosis (rabbit)",
    # Hyperthyroidism is a thyroid disorder — INLINE_INFO is correct, do not alias to Diabetes
    "Pancreatitis":                       "Gastrointestinal and Digestive Disorders (cats and Dogs)",
    "Giardiasis":                         "Gastrointestinal and Digestive Disorders (cats and Dogs)",
    "Cryptosporidiosis":                  "Calf Scour",
    "Fungal Infection":                   "Ringworm",
    "West Nile Virus":                    "Equine West Nile Virus",
}

# ── Inline disease info for diseases with no info-file entry ─────────────────
INLINE_INFO: dict = {
    "Actinobacillus Pleuropneumonia": {
        "description": "A highly contagious bacterial respiratory disease caused by Actinobacillus pleuropneumoniae, primarily affecting pigs. It leads to severe pleuropneumonia with sudden death in acute cases or chronic lung damage in survivors.",
        "treatment": "Antibiotics such as penicillin, ceftiofur, or florfenicol administered early;Anti-inflammatory drugs to reduce fever and lung inflammation;Supportive care including fluids and rest.",
        "prevention": "Vaccination programs using available bacterins;Strict biosecurity — isolate new animals for at least 4 weeks;Avoid stress and overcrowding;Proper ventilation in housing;Regular health monitoring."
    },
    "Actinobacillus Suis": {
        "description": "A bacterial infection in pigs caused by Actinobacillus suis, leading to septicemia, pneumonia, and skin hemorrhages. Young pigs under 8 weeks are most susceptible.",
        "treatment": "Prompt antibiotic treatment with penicillin or amoxicillin;Supportive care including fluids and warmth;Isolate affected animals to prevent spread.",
        "prevention": "Maintain excellent hygiene in farrowing areas;Ensure sow health and proper colostrum intake for piglets;Reduce stress and overcrowding;Implement proper biosecurity protocols."
    },
    "Allergic Rhinitis": {
        "description": "An inflammatory condition of the nasal passages triggered by allergens such as pollen, dust, mold, or food. Common in dogs and cats, presenting with chronic sneezing, nasal discharge, and nasal congestion.",
        "treatment": "Antihistamines such as cetirizine or chlorphenamine;Corticosteroids for severe cases;Allergen identification and avoidance;Nasal saline rinse to clear discharge;Immunotherapy (allergy shots) for long-term management.",
        "prevention": "Minimize exposure to known allergens;Use air purifiers indoors;Regular grooming to remove pollen from fur;Avoid smoking near pets;Schedule regular vet check-ups to monitor respiratory health."
    },
    "Bordetella Infection": {
        "description": "Caused by Bordetella bronchiseptica bacteria, this highly contagious respiratory infection affects dogs, cats, rabbits and other animals. A major cause of kennel cough, producing a harsh, honking cough.",
        "treatment": "Antibiotics such as doxycycline or azithromycin for 1-2 weeks;Cough suppressants for symptom relief;Isolation of infected animals;Supportive care with hydration and rest.",
        "prevention": "Vaccination — Bordetella vaccines are available for dogs and cats;Avoid boarding facilities with poor hygiene;Minimize contact with unknown animals;Ensure proper ventilation in kennels and catteries."
    },
    "Bovine Johne's Disease": {
        "description": "A chronic, progressive, and fatal bacterial infection of the small intestine in cattle and other ruminants caused by Mycobacterium avium paratuberculosis. It leads to malabsorption, protein loss, and profuse watery diarrhea.",
        "treatment": "There is no practical cure for clinical Johne's Disease;Management focuses on controlling spread within the herd;Remove and cull clinical animals;Supportive care to maintain quality of life in sub-clinical animals.",
        "prevention": "Test-and-cull program for infected animals;Prevent calves from contact with infected manure;Source replacement animals from Johne's-free herds;Disinfect calving areas thoroughly;Implement strict biosecurity protocols."
    },
    "Bovine Leukemia Virus": {
        "description": "A retrovirus causing bovine leukosis — the most common neoplastic disease of cattle worldwide. Most infected animals are asymptomatic carriers, but a small percentage develop lymphoma and enlarged lymph nodes.",
        "treatment": "No effective treatment or cure exists;Management focuses on controlling herd spread;Cull lymphoma-positive animals;Maintain herd productivity through monitoring.",
        "prevention": "Test regularly using ELISA or AGID blood tests;Use single-use needles and surgical equipment;Control biting insects that may spread the virus;Cull seropositive animals in highly managed herds;Purchase replacements from BLV-free herds."
    },
    "Bovine Parainfluenza": {
        "description": "A viral respiratory disease of cattle caused by Bovine Parainfluenza Virus-3 (BPIV-3), contributing to Bovine Respiratory Disease Complex. It causes fever, nasal discharge, and coughing, often acting as a gateway for secondary bacterial infections.",
        "treatment": "Anti-inflammatory drugs (NSAIDs) to reduce fever;Antibiotics for secondary bacterial infections;Supportive care including hydration and good nutrition;Rest in a clean, well-ventilated area.",
        "prevention": "Vaccinate cattle with combination respiratory vaccines that include BPIV-3;Reduce stress during transportation and weaning;Maintain good ventilation and reduce crowding;Implement proper biosecurity when introducing new animals."
    },
    "Bovine Respiratory Disease Complex": {
        "description": "The most economically costly disease in the cattle industry, caused by a combination of environmental stress, viral infections (IBR, BVDV, BRSV, PI3), and secondary bacterial infections (Mannheimia haemolytica, Pasteurella multocida). Also known as shipping fever.",
        "treatment": "Antibiotics — florfenicol, tulathromycin, or enrofloxacin;Anti-inflammatory drugs (flunixin meglumine or meloxicam) for fever;Early treatment is critical — pull animals at first signs;Supportive care.",
        "prevention": "Pre-condition cattle before shipping — vaccinate and deworm 3-4 weeks before;Use combination BRD vaccines;Reduce stress during transport — minimize duration and crowding;Ensure proper nutrition and vitamin E/selenium status;Provide fresh water and good quality feed immediately on arrival."
    },
    "Bovine Respiratory Syncytial Virus": {
        "description": "BRSV causes severe lower respiratory tract disease in cattle, particularly in young calves under 6 months. It causes bronchiolitis and interstitial pneumonia, leading to respiratory distress and sometimes death.",
        "treatment": "Supportive care — ensure clean air and warmth;Anti-inflammatory NSAIDs to reduce fever and inflammation;Antibiotics for secondary bacterial pneumonia;In severe cases, bronchodilators may help.",
        "prevention": "Vaccination with modified live or killed BRSV vaccines;Colostrum intake in neonatal calves;Reduce overcrowding and improve ventilation;Minimize stress and mixing of age groups."
    },
    "Canine Cough": {
        "description": "An infectious tracheobronchitis complex causing a distinctive dry, hacking cough in dogs, often ending with a gagging or retching sound. Highly contagious in kennels, dog parks, and grooming facilities.",
        "treatment": "Most cases resolve without treatment in 1-3 weeks;Antibiotics (doxycycline) if bacterial component is severe;Cough suppressants for comfort;Rest from exercise;Humidified air to soothe airways.",
        "prevention": "Annual Bordetella vaccination for dogs in contact with other dogs;Avoid kennels, dog parks during outbreaks;Ensure good ventilation in kennels;Quarantine new dogs before introducing to others."
    },
    "Canine Flu": {
        "description": "Canine influenza is a highly contagious respiratory disease in dogs caused by influenza A viruses (H3N8 or H3N2). Symptoms include coughing, nasal discharge, fever, and lethargy. Nearly all exposed dogs get infected.",
        "treatment": "Supportive care — rest, fluids, good nutrition;Antibiotics for secondary bacterial pneumonia;Anti-inflammatory drugs for fever;Cough suppressants;Hospitalization for severe cases.",
        "prevention": "Bivalent canine influenza vaccine (H3N8 and H3N2) for at-risk dogs;Avoid contact with infected dogs;Disinfect surfaces — the virus survives up to 48 hours on surfaces;Isolate infected dogs for 4 weeks."
    },
    "Canine Heartworm Disease": {
        "description": "A life-threatening parasitic infection caused by Dirofilaria immitis, transmitted by mosquitoes. Worms grow in the heart, lungs, and blood vessels, causing severe lung disease and heart failure if untreated.",
        "treatment": "Melarsomine injections (Immiticide) to kill adult worms — requires exercise restriction;Pre-treatment with doxycycline to reduce Wolbachia bacteria;Monthly heartworm preventive given for several months;Supportive care during treatment;Surgery in severe caval syndrome cases.",
        "prevention": "Year-round monthly heartworm preventives (ivermectin, milbemycin);Annual heartworm testing;Mosquito control in environment;Do not skip prevention in winter months."
    },
    "Canine Leptospirosis": {
        "description": "A bacterial infection caused by Leptospira spirochetes, spread through contact with contaminated water, soil, or urine of infected animals. It can cause kidney and liver failure and is also a zoonotic disease — transmissible to humans.",
        "treatment": "Antibiotics — penicillin initially, then doxycycline for 2 weeks to eliminate carrier state;IV fluids for kidney and liver support;Dialysis in severe acute kidney injury;Isolate infected dogs as zoonotic risk.",
        "prevention": "Annual Leptospirosis vaccination (4-serovar vaccine recommended);Avoid exposure to wildlife urine, slow-moving water, and floodwater;Wear gloves when handling infected animals;Keep rodents out of the environment."
    },
    "Canine Parvovirus": {
        "description": "An extremely contagious and potentially fatal viral disease caused by CPV-2. It attacks the gastrointestinal tract and immune system, causing severe vomiting, bloody diarrhea, dehydration, and sepsis. Puppies under 6 months are most at risk.",
        "treatment": "Intensive hospitalization with IV fluids and electrolytes;Antibiotics to prevent secondary infections;Anti-nausea and anti-vomiting medications;Plasma or blood transfusions in severe cases;No specific antiviral — treatment is supportive.",
        "prevention": "Complete the puppy vaccination series — DHPP vaccine at 6, 8, 12, and 16 weeks;Annual boosters for adult dogs;Avoid contact with unvaccinated dogs or contaminated soil;The virus survives in environment for 1 year — disinfect with bleach."
    },
    "Caprine Arthritis Encephalitis": {
        "description": "A slow, progressive viral disease of goats caused by Caprine Arthritis Encephalitis Virus (CAEV). Adult goats develop chronic arthritis while young kids may show neurological symptoms. There is no cure.",
        "treatment": "No treatment or cure available;Anti-inflammatory drugs to improve quality of life;Nutritional support with good quality feed;Cull severely affected animals.",
        "prevention": "Test all animals regularly and cull positive animals;Separate kids immediately at birth and feed heat-treated colostrum;Source animals from tested CAEV-negative herds;Strict biosecurity — do not share needles or equipment."
    },
    "Caprine Pleuropneumonia": {
        "description": "Contagious Caprine Pleuropneumonia (CCPP) is caused by Mycoplasma capricolum subspecies capripneumoniae. It is an OIE-notifiable disease causing severe respiratory distress, pleurisy, and high mortality in goats.",
        "treatment": "Oxytetracycline and tylosin antibiotics can reduce mortality if given early;Supportive care including rest and fluids;Isolate affected animals;Notify veterinary authorities as it is a notifiable disease.",
        "prevention": "Vaccination with available bacterins where approved;Strict border controls and movement restrictions;Quarantine imported animals;Rapid reporting to authorities at suspicion of outbreak."
    },
    "Caprine Respiratory Disease": {
        "description": "A complex of respiratory conditions in goats caused by multiple pathogens including Pasteurella multocida, Mannheimia haemolytica, and Mycoplasma species. Symptoms include nasal discharge, coughing, and respiratory distress.",
        "treatment": "Antibiotics appropriate to causative organism;Anti-inflammatory drugs to reduce fever;Supportive care and isolation;Vitamin supplementation to support immunity.",
        "prevention": "Maintain good ventilation and reduce overcrowding;Minimize stress — especially during weaning and transport;Vaccinate against known pathogens;Ensure adequate colostrum intake in kids."
    },
    "Caseous Lymphadenitis": {
        "description": "A chronic bacterial disease of sheep and goats caused by Corynebacterium pseudotuberculosis. Characterized by abscess formation in superficial lymph nodes and internal organs, reducing productivity and carcass value.",
        "treatment": "Surgical drainage of abscesses with disinfection of site;Antibiotics are minimally effective;Formalin-inactivated vaccines available;Cull chronic shedders.",
        "prevention": "Vaccinate in endemic areas;Isolate animals with abscesses;Disinfect shearing and surgical equipment;Test purchased animals before introduction;Maintain closed flock/herd where possible."
    },
    "Chlamydia in Sheep": {
        "description": "Ovine chlamydiosis caused by Chlamydia abortus is the most common infectious cause of abortion in sheep in many countries (Enzootic Abortion of Ewes). It can also infect humans — particularly dangerous for pregnant women.",
        "treatment": "Oxytetracycline given to pregnant ewes at risk;Treat aborted ewes with antibiotics;Zoonotic risk — handle aborted material with gloves and care.",
        "prevention": "Vaccination of replacement ewes before first pregnancy;Keep sheep away from other flocks during lambing;Dispose of aborted material safely and hygienically;Pregnant women should avoid contact with lambing sheep."
    },
    "Chronic Bronchitis": {
        "description": "A persistent inflammation of the bronchi causing a productive cough lasting more than two months, common in middle-aged to older dogs. Irreversible airway changes occur over time, but symptoms can be managed.",
        "treatment": "Corticosteroids (prednisolone) to reduce airway inflammation;Bronchodilators to open airways;Antibiotics if secondary infection is present;Weight management — obesity worsens symptoms;Avoid smoke and dusty environments.",
        "prevention": "Avoid smoke, aerosol sprays, and dusty environments;Maintain a healthy body weight;Regular vet check-ups for early detection;Prompt treatment of respiratory infections to prevent chronicity."
    },
    "Conjunctivitis": {
        "description": "Inflammation of the conjunctiva (the membrane lining the eyelids), causing redness, discharge, and discomfort. Common in dogs, cats, rabbits, and livestock. Can be infectious (bacterial, viral) or non-infectious (allergic, environmental).",
        "treatment": "Topical antibiotic eye drops or ointment for bacterial conjunctivitis;Antihistamine or steroid eye drops for allergic conjunctivitis;Gently clean discharge from the eyes;Remove the underlying cause (foreign body, allergen);Antiviral treatment if caused by herpesvirus in cats.",
        "prevention": "Keep the eye area clean;Treat upper respiratory infections promptly as they can spread to eyes;Minimize exposure to irritants such as dust, smoke, and chemicals;Regular veterinary eye examinations for high-risk breeds."
    },
    "Contagious Abortion": {
        "description": "Also known as Brucellosis, caused by Brucella abortus in cattle, Brucella melitensis in sheep and goats. Causes reproductive failure — abortions in females and orchitis in males. Highly contagious and zoonotic.",
        "treatment": "No effective treatment in animals;Slaughter and compensation programs are used in national eradication schemes;Antibiotics used in humans affected zoonotically.",
        "prevention": "Vaccination — S19 or RB51 vaccines in cattle;Test-and-slaughter national programs;Strict hygiene when handling aborted material;Zoonotic disease — use gloves and masks when handling afterbirths."
    },
    "Contagious Ecthyma": {
        "description": "Also called Orf or Scabby Mouth, caused by a parapoxvirus. It causes proliferative skin lesions (pustules and scabs) around the mouth, nostrils, and feet in sheep and goats. Also a zoonotic disease.",
        "treatment": "Self-limiting — most cases resolve in 3-6 weeks;Keep lesions clean and free of flies;Topical antiseptic ointments;Isolate affected animals;Soft feed to allow eating despite mouth pain.",
        "prevention": "Vaccination with live attenuated orf vaccine;Handle affected animals with gloves as it transmits to humans;Quarantine new animals before introducing to the flock."
    },
    "Cryptosporidiosis": {
        "description": "A parasitic disease caused by Cryptosporidium parvum, most severe in young calves, lambs, and kids. Causes profuse watery diarrhea and can be rapidly fatal in neonates due to dehydration. Zoonotic potential.",
        "treatment": "Oral or IV rehydration therapy is the cornerstone of treatment;Halofuginone (licensed in calves) to reduce oocyst shedding;Good nursing care — warm, dry bedding;No fully effective drug treatment — supportive care essential.",
        "prevention": "Isolate affected neonates immediately;Ensure adequate colostrum intake in the first hours of life;Clean and disinfect maternity pens between uses;Reduce stocking density;Wash hands thoroughly after handling calves."
    },
    "Degenerative Joint Disease": {
        "description": "Also known as osteoarthritis, this progressive condition causes deterioration of joint cartilage and underlying bone in dogs, cats, and horses. Leading to pain, stiffness, and reduced mobility, particularly in older or large breed animals.",
        "treatment": "NSAIDs such as carprofen or meloxicam for pain management;Omega-3 fatty acid supplements;Glucosamine and chondroitin supplements;Physical therapy and controlled low-impact exercise;Weight management;In severe cases, joint surgery.",
        "prevention": "Maintain healthy body weight throughout life;Provide low-impact exercise (swimming);Feed joint-supporting supplements from middle age in at-risk breeds;Screen large breed puppies for hip and elbow dysplasia."
    },
    "Digestive Issues": {
        "description": "A broad category of gastrointestinal conditions affecting digestion, absorption, or motility. Causes range from dietary indiscretion, infections, parasites, stress, and food allergies to more serious conditions like IBD or cancer.",
        "treatment": "Bland diet — boiled chicken and rice for dogs and cats;Probiotics to restore healthy gut flora;Antibiotics if bacterial infection is confirmed;Anti-parasitic medications if parasites are identified;Fluid therapy for dehydration.",
        "prevention": "Feed consistent, high-quality food;Avoid sudden diet changes — transition over 7-10 days;Regular deworming;Avoid letting pets eat garbage or foreign material;Ensure clean, fresh water is always available."
    },
    "Ear Infections": {
        "description": "Otitis externa — inflammation of the outer ear canal — commonly caused by bacteria (Staphylococcus, Pseudomonas), yeast (Malassezia), or parasites (Otodectes mites). Very common in dogs with floppy ears. Causes head shaking, scratching, and odor.",
        "treatment": "Thorough ear cleaning with veterinary-approved cleanser;Topical ear drops with antibiotics and/or antifungals;Treat underlying causes — allergies, hypothyroidism;Anti-parasitic treatment if mites are present;Systemic antibiotics for deep infections.",
        "prevention": "Regular ear cleaning, especially after swimming or bathing;Keep ears dry;Address underlying allergies;Check and clean ears weekly in floppy-eared breeds;Annual ear health checks with your veterinarian."
    },
    "Enteritis": {
        "description": "Inflammation of the small intestine causing diarrhea, vomiting, abdominal pain, and dehydration. Can be caused by bacteria (Salmonella, E. coli), viruses (parvovirus, coronavirus), or parasites. Severity ranges from mild to life-threatening.",
        "treatment": "Rehydration therapy — oral or IV fluids;Bland diet;Antibiotics if bacterial cause is confirmed;Anti-parasitic treatment if parasites identified;Anti-nausea medication.",
        "prevention": "Vaccination against viral causes (parvovirus);Regular deworming program;Avoid exposure to contaminated food and water;Maintain good hygiene in animal housing;Quarantine new animals."
    },
    "Equine Arthritis": {
        "description": "Inflammation of one or more joints in horses, causing lameness and pain. Common forms include infectious arthritis (septic arthritis), degenerative joint disease (DJD), and traumatic arthritis. Front fetlock and coffin joints are commonly affected.",
        "treatment": "NSAIDs such as phenylbutazone or flunixin meglumine;Intra-articular corticosteroid injections;Hyaluronic acid joint injections;Rest and controlled rehabilitation;In severe cases, surgical joint fusion (arthrodesis).",
        "prevention": "Maintain a consistent exercise program on good footing;Correct hoof balance with regular farriery;Avoid excessive work on hard surfaces;Early treatment of joint injuries;Regular veterinary lameness evaluations."
    },
    "Equine Cushing's Disease": {
        "description": "Also called Pituitary Pars Intermedia Dysfunction (PPID), this progressive hormonal disorder in older horses causes a distinctive curly coat, muscle wasting, pot belly, and laminitis due to elevated ACTH levels.",
        "treatment": "Pergolide (Prascend) — the primary and most effective treatment, given daily for life;Regular body condition scoring and coat clipping;Dental care;Supportive nutrition with low-sugar diet.",
        "prevention": "No prevention possible — manage with early detection;Annual blood tests (ACTH) for horses over 15 years;Provide a low-starch, low-sugar diet;Regular farriery to prevent laminitis."
    },
    "Equine Encephalitis": {
        "description": "Viral encephalomyelitis in horses caused by Eastern (EEE), Western (WEE), or Venezuelan (VEE) equine encephalitis viruses, transmitted by mosquitoes. Causes fever, neurological signs, and often death.",
        "treatment": "Supportive care only — no antiviral treatment available;IV fluids and anti-inflammatory drugs;Anti-seizure medications as needed;Nursing care — padded stalls for recumbent horses.",
        "prevention": "Annual vaccination against EEE, WEE, and VEE;Mosquito control — eliminate standing water and use insect repellent;Keep horses stabled during peak mosquito hours (dusk to dawn);Vaccination boosters in high-risk areas."
    },
    "Equine Encephalomyelitis": {
        "description": "An inflammatory disease of the brain and spinal cord in horses, typically caused by viral encephalitis viruses (EEE, WEE, VEE) transmitted by mosquitoes. Neurological signs include incoordination, behavioral changes, and recumbency.",
        "treatment": "Supportive care with IV fluids and anti-inflammatories;Anti-seizure medications if needed;Intensive nursing care;Slings for horses unable to stand;Prognosis is guarded to poor for severe cases.",
        "prevention": "Vaccination is highly effective;Control mosquito populations;Avoid outdoor activity during peak mosquito hours;Report suspected cases to authorities."
    },
    "Equine Herpesvirus": {
        "description": "Equine Herpesvirus (EHV-1 and EHV-4) cause respiratory disease, abortion storms, and sometimes neurological disease (EHM) in horses. Highly contagious through direct contact and respiratory secretions.",
        "treatment": "Supportive care — rest and anti-inflammatory treatment;Antiviral drug valacyclovir for neurological cases;Isolate affected horses immediately;Antibiotics for secondary respiratory infections.",
        "prevention": "Vaccination — reduces severity but does not fully prevent infection;Strict biosecurity at competitions and shows;Quarantine new arrivals for 3 weeks;Regular veterinary surveillance during outbreaks."
    },
    "Equine Infectious Anemia": {
        "description": "Swamp fever — a blood-borne viral disease of horses caused by Equine Infectious Anemia Virus (EIAV), transmitted by biting flies. Causes fever, anemia, weight loss, and edema in acute cases; chronic carriers are a persistent reservoir.",
        "treatment": "No effective treatment or cure;Euthanasia or permanent quarantine of Coggins-positive horses required by law in most countries.",
        "prevention": "Annual Coggins test (AGID) required for competitions and transport;Use sterile needles and equipment;Control biting insects;Isolate positive horses immediately and report to authorities."
    },
    "Equine Influenza": {
        "description": "A highly contagious respiratory disease of horses caused by Equine Influenza Virus (H3N8), spread rapidly through equine populations. Causes sudden fever, dry cough, nasal discharge, and lethargy. Young horses are most severely affected.",
        "treatment": "Complete rest — minimum 1 week plus 1 week per day of fever;Anti-inflammatory drugs for fever and discomfort;Antibiotics for secondary bacterial infections;Good nutrition and water intake.",
        "prevention": "Regular vaccination — minimum every 6 months in competition horses;Biosecurity at shows and competitions;Quarantine new horses for 3 weeks;Avoid nose-to-nose contact between horses from different yards."
    },
    "Equine Influenza Virus": {
        "description": "The causative agent of equine influenza — H3N8 influenza A virus. Spreads extremely rapidly between horses through aerosol droplets. Can affect an entire stable within days of introduction of one infected horse.",
        "treatment": "Rest is the primary treatment;Anti-inflammatory NSAIDs for fever and comfort;Antibiotics if secondary pneumonia develops;Supportive care with good nutrition.",
        "prevention": "Six-monthly vaccination in high-risk horses;Quarantine all new arrivals;Biosecurity during outbreaks;Nasal swabs for early diagnosis."
    },
    "Equine Laminitis": {
        "description": "A painful and potentially crippling condition of the horse's feet involving inflammation of the sensitive laminae within the hoof. Can result in rotation or sinking of the pedal bone. Triggered by grain overload, lush grass, Cushing's disease, or severe systemic illness.",
        "treatment": "Emergency treatment — remove from pasture immediately;Deep, supportive bedding (sand);Frog support pads and corrective shoeing;NSAIDs — phenylbutazone for pain;Treat the underlying cause;Regular farriery every 6-8 weeks.",
        "prevention": "Limit access to rich spring or autumn pasture;Gradual introduction to new grass;Feed low-starch, low-sugar diet;Manage Cushing's disease proactively;Maintain healthy body weight."
    },
    "Equine Metabolic Syndrome": {
        "description": "A hormonal disorder in horses and ponies characterized by obesity (especially cresty neck), insulin dysregulation, and predisposition to laminitis. Distinct from but often co-existing with PPID (Cushings).",
        "treatment": "Dietary management — low-starch, low-sugar forage;Increase exercise;Weight loss program;Thyro-L (levothyroxine) to support metabolic rate;Treat concurrent laminitis;Monitor insulin levels.",
        "prevention": "Maintain healthy body condition score 4-5 out of 9;Restrict access to lush, sugar-rich pasture;Feed hay soaked in water for 30-60 minutes to reduce sugar;Regular exercise;Annual blood glucose and insulin testing."
    },
    "Equine Pneumonia": {
        "description": "Bacterial or viral pneumonia in horses, most commonly caused by Streptococcus zooepidemicus, Rhodococcus equi (in foals), or viral agents such as EHV or Equine Influenza. Causes fever, nasal discharge, labored breathing, and reduced performance.",
        "treatment": "Broad-spectrum antibiotics — penicillin/gentamicin or trimethoprim-sulfonamide;NSAIDs such as phenylbutazone or flunixin meglumine for fever;Complete rest from exercise;Supportive care — good nutrition, hydration, clean air;Nebulization therapy in severe cases.",
        "prevention": "Vaccination against Equine Influenza and EHV-1/4;Quarantine new horses for 3 weeks;Reduce stress and overcrowding;Proper ventilation in stabling;Avoid moving horses during active respiratory outbreaks."
    },
    "Equine Osteoarthritis": {
        "description": "Progressive deterioration of joint cartilage in horses causing chronic pain and lameness. Most commonly affects the hock, fetlock, and pastern joints. A leading cause of performance loss in sport horses.",
        "treatment": "Intra-articular corticosteroids and hyaluronic acid injections;NSAIDs for daily pain management;Stem cell therapy or PRP injections;Corrective shoeing by experienced farrier;Modified exercise program.",
        "prevention": "Regular farriery for correct hoof balance;Age-appropriate and surface-appropriate exercise;Early lameness investigations;Joint supplements from middle age in performance horses."
    },
    "Equine Piroplasmosis": {
        "description": "A tick-transmitted blood parasite infection in horses caused by Theileria equi or Babesia caballi, causing fever, anemia, jaundice, and sometimes death. An OIE-notifiable disease.",
        "treatment": "Imidocarb dipropionate — the primary treatment drug;Supportive care including IV fluids and blood transfusions;Tick removal and environmental tick control.",
        "prevention": "Rigorous tick control using acaricides;Inspect horses daily for ticks;Quarantine and test imported horses;Report any confirmed cases to authorities."
    },
    "Equine Protozoal Myeloencephalitis": {
        "description": "A neurological disease of horses caused by Sarcocystis neurona (and less commonly Neospora hughesi), transmitted through opossum feces in North America. Causes progressive, asymmetric neurological signs.",
        "treatment": "Antiprotozoal drugs — diclazuril or ponazuril for 3-6 months;Anti-inflammatory corticosteroids early in disease;Vitamin E supplementation for nerve support;Physical therapy and supportive nursing.",
        "prevention": "Prevent horse access to opossum feces — secure feed storage;Do not feed on the ground where opossums travel;Reduce stress which may activate latent infections;Ponazuril prophylaxis in highly endemic areas."
    },
    "Equine Rhinopneumonitis": {
        "description": "Caused by Equine Herpesvirus 1 and 4, rhinopneumonitis causes respiratory disease in horses, with EHV-1 also associated with abortion outbreaks and occasionally neurological disease.",
        "treatment": "Rest and supportive care;Anti-inflammatory drugs;Antiviral therapy (valacyclovir) for EHM cases;Isolate infected horses immediately.",
        "prevention": "Regular EHV vaccination;Quarantine new arrivals and competition returnees;Thorough disinfection of stabling areas;Strict biosecurity at shows."
    },
    "Equine Viral Arteritis": {
        "description": "An OIE-notifiable disease of horses caused by Equine Arteritis Virus (EAV), causing respiratory disease, edema, abortion in mares, and persistent infection in stallions. Spreads via respiratory aerosols and venereal transmission.",
        "treatment": "Supportive care — rest, anti-inflammatory drugs, fluids;Stallions may remain persistently infected carriers;No specific antiviral treatment.",
        "prevention": "Vaccination of stallions before the breeding season;Serological testing of stallions before breeding;AI from seropositive stallions should be managed carefully;Biosecurity at competitions."
    },
    "Equine West Nile Virus": {
        "description": "West Nile Virus infects horses via Culex mosquito bites, causing encephalitis and myelitis. Mortality is around 30% in clinical cases and neurological damage can persist in survivors.",
        "treatment": "Supportive care only — no specific antiviral;NSAIDs for fever and inflammation;Intensive nursing for recumbent horses;Physical therapy during recovery.",
        "prevention": "Vaccination — highly effective WNV vaccines available;Mosquito control — eliminate standing water;Stable horses during peak mosquito activity (dusk to dawn);Annual vaccination boosters."
    },
    "Feline Asthma": {
        "description": "A chronic allergic airway disease in cats causing recurrent episodes of airway inflammation and bronchoconstriction. Triggered by allergens, stress, or irritants. Cats present with a characteristic crouching, wheezy cough.",
        "treatment": "Corticosteroids to control inflammation — prednisolone or inhaled fluticasone;Bronchodilators — terbutaline or salbutamol inhaler via AeroKat spacer;Identify and eliminate triggers;Emergency treatment with adrenaline for acute attacks.",
        "prevention": "Eliminate allergen triggers — avoid dusty litter, aerosol sprays, cigarette smoke;Use low-dust cat litter;Air purifiers in the home;Regular vet check-ups to monitor lung function;Keep rescue inhaler available."
    },
    "Feline Calicivirus": {
        "description": "A common cause of upper respiratory infection and oral disease (stomatitis, mouth ulcers) in cats. Highly contagious between cats, spreads via direct contact and contaminated environments. Some strains cause limping syndrome.",
        "treatment": "Supportive care — fluids, nutritional support, warmth;Antibiotics for secondary bacterial infections;Analgesics for mouth pain;Appetite stimulants if anorexic;In severe cases, hospitalization.",
        "prevention": "Core vaccination — FCV is part of the FVRCP vaccine;Boost annually in cats at risk;Keep cats indoors to reduce exposure;Disinfect environment with bleach-based products;Quarantine new cats."
    },
    "Feline Chlamydia": {
        "description": "Caused by Chlamydia felis, this bacterial infection is a significant cause of feline conjunctivitis, with concurrent mild upper respiratory signs. Persistent infection is common without appropriate treatment.",
        "treatment": "Doxycycline antibiotic for a full 6-week course;Topical chloramphenicol eye ointment;Treat all in-contact cats simultaneously;Clean eye discharge daily.",
        "prevention": "Vaccination available — recommended for cats at high risk (multi-cat households, breeders);Treat all cats in the household;Quarantine new cats;Regular hand hygiene when handling infected cats."
    },
    "Feline Coronavirus": {
        "description": "Feline Coronavirus (FCoV) is ubiquitous in multi-cat households. The common form causes mild diarrhea. In a small percentage of cats, the virus mutates to cause Feline Infectious Peritonitis (FIP) — a progressive, historically fatal disease.",
        "treatment": "For FIP: GS-441524 antiviral drug — highly effective in recent studies;Supportive care — draining effusions, steroids for wet FIP;Nutritional support;Regular monitoring of protein levels.",
        "prevention": "Reduce stress and overcrowding in multi-cat environments;Separate litter boxes for individual cats;Quarantine new cats;FELV-FIP vaccination available but not universally recommended."
    },
    "Feline Immunodeficiency Virus": {
        "description": "FIV is a retrovirus affecting cats worldwide, similar to HIV in humans. Transmitted mainly through bite wounds. Most infected cats live a normal lifespan but are immunosuppressed, making them vulnerable to opportunistic infections.",
        "treatment": "No cure — management focuses on quality of life;Treat secondary infections promptly;Anti-retroviral drugs (AZT) in some cases;High-quality nutrition;Regular vet monitoring every 6 months.",
        "prevention": "Keep cats indoors to prevent fighting;Neuter cats to reduce fighting behavior;FIV vaccine available in some countries;Test all cats before introducing to a FIV-negative household;Do not share food bowls with unknown cats."
    },
    "Feline Infectious Peritonitis": {
        "description": "FIP is caused by a mutated form of Feline Coronavirus. It causes either wet FIP (fluid accumulation in chest/abdomen) or dry FIP (granulomas in organs/brain). Historically fatal, but GS-441524 antiviral is now highly curative.",
        "treatment": "GS-441524 antiviral — 84-day course, highly effective;Prednisolone to control inflammation early;Drain effusions for immediate respiratory relief;Regular monitoring of blood proteins and organ function.",
        "prevention": "Reduce FCoV exposure by reducing cat density and stress;Separate litter boxes per cat in multi-cat households;Quarantine new cats;Avoid high-FCoV environments for immunocompromised cats."
    },
    "Feline Leukemia": {
        "description": "A disease caused by Feline Leukemia Virus (FeLV) causing immunosuppression, anemia, lymphoma, and other cancers in cats. Transmitted through saliva, nasal secretions, and shared food bowls. A major cause of death in young cats.",
        "treatment": "No cure — supportive care to manage symptoms;Treat opportunistic infections;Anti-cancer chemotherapy for lymphoma;Immune-stimulating drugs in some cases;Regular blood monitoring.",
        "prevention": "Vaccination — FeLV vaccine is core for at-risk cats;Test all cats before introducing to a FeLV-negative household;Keep cats indoors;Test and separate FeLV-positive cats."
    },
    "Feline Leukemia Virus": {
        "description": "The causative retrovirus of Feline Leukemia. It integrates into the cat's genome after infection. Progressive viral infection (p-FeLV) leads to bone marrow suppression, lymphoma, and immune failure. Regressive infection (r-FeLV) often resolves without disease.",
        "treatment": "Supportive care for clinical disease;Chemotherapy protocols for lymphoma;Blood transfusions for severe anemia;Monitor for secondary infections.",
        "prevention": "Vaccination is the most effective prevention;Test before adoption or introducing new cats;Keep at-risk cats indoors;Test blood regularly in positive-status cats."
    },
    "Feline Panleukopenia": {
        "description": "A highly contagious and often fatal viral disease of cats caused by Feline Parvovirus (FPV). Similar to canine parvovirus, it destroys rapidly dividing cells causing severe enteritis, bone marrow suppression, and is frequently fatal in kittens.",
        "treatment": "Intensive hospitalization with IV fluids;Antibiotics for secondary sepsis;Antinausea drugs;Blood transfusions for severe bone marrow suppression;Interferon-omega in some cases.",
        "prevention": "Core vaccination — part of FVRCP vaccine;Complete the kitten series at 6, 8, 12, and 16 weeks;Annual or triennial boosters;Isolate infected cats — the virus persists in the environment for 1+ year;Disinfect with sodium hypochlorite."
    },
    "Feline Panleukopenia Virus": {
        "description": "Feline Parvovirus — an extremely stable virus in the environment, resistant to most common disinfectants. It can survive for over a year on surfaces, making environmental contamination a major infection source even in vaccinated populations.",
        "treatment": "Intensive supportive care is the only option;IV fluids with electrolyte correction;Antiemetics and antibiotics;Transfusion if severely anemic;Quarantine of all infected cats.",
        "prevention": "Vaccination is highly protective;Disinfect with bleach 1:32 dilution;Do not bring unvaccinated cats into contaminated environments;Quarantine new cats for 2-3 weeks."
    },
    "Feline Renal Disease": {
        "description": "Chronic Kidney Disease (CKD) is the most common disease in older cats, affecting over 30% of cats over 15 years. Kidneys gradually lose their filtering capacity, leading to toxin accumulation, anemia, hypertension, and reduced quality of life.",
        "treatment": "Phosphate-restricted renal diet;Sub-cutaneous fluid therapy at home;ACE inhibitors for hypertension;Phosphate binders;Erythropoietin for anemia;Regular blood pressure and kidney value monitoring.",
        "prevention": "Ensure adequate water intake — use water fountains;Feed wet food rather than dry;Annual urine and blood testing from age 7;Maintain healthy body weight;Avoid nephrotoxic drugs like NSAIDs and aminoglycosides."
    },
    "Fungal Infection": {
        "description": "Fungal infections in animals include dermatophytosis (ringworm), aspergillosis, cryptococcosis, and candidiasis. They affect skin, lungs, or systemic organs depending on the fungal species and the animal's immune status.",
        "treatment": "Antifungal drugs — itraconazole, fluconazole, or voriconazole depending on the fungus;Topical antifungal shampoos and creams for skin infections;Long treatment courses are usually required (weeks to months);Treat the environment as well as the animal.",
        "prevention": "Maintain good hygiene and ventilation;Minimize stress;Isolate animals with ringworm;Treat all in-contact animals simultaneously;Disinfect environment — fungi can persist on surfaces."
    },
    "Gastroenteritis": {
        "description": "Inflammation of the stomach and intestinal tract causing vomiting, diarrhea, nausea, and abdominal pain. Common in dogs and cats from dietary indiscretion, infections (parvovirus, salmonella), parasites, or toxin ingestion.",
        "treatment": "Fasting for 12-24 hours then bland diet;Oral rehydration — IV fluids if severely dehydrated;Anti-nausea drugs (metoclopramide, maropitant);Antibiotics if bacterial cause confirmed;Probiotics to restore gut flora.",
        "prevention": "Feed a consistent, high-quality diet;Avoid table scraps and garbage;Prevent access to toxic plants and household chemicals;Keep fresh clean water available;Annual vaccination against viral gastroenteritis."
    },
    "Gastrointestinal Infection": {
        "description": "Infection of the gastrointestinal tract caused by bacteria (Salmonella, E. coli, Campylobacter), viruses (parvovirus, rotavirus), or parasites (Giardia, Cryptosporidium). Causes diarrhea, vomiting, and variable systemic signs.",
        "treatment": "Rehydration therapy;Antibiotics if bacterial cause confirmed;Anti-parasitic treatment if parasites identified;Supportive nutrition — bland, easily digestible diet;Probiotics.",
        "prevention": "Vaccination against common viral agents;Good hygiene in feeding and water management;Regular deworming;Quarantine new animals;Avoid contact with infected animals or their feces."
    },
    "Gastrointestinal Stasis": {
        "description": "In rabbits and guinea pigs, GI stasis is a potentially fatal slowing or complete halt of gut motility. Causes severe discomfort, gas accumulation, and rapid deterioration. Often triggered by pain, stress, inappropriate diet, or dehydration.",
        "treatment": "Emergency — do not wait;Syringe feed critical care food;Oral fluid supplementation;Pain relief (meloxicam) to reduce gut spasm;Gut motility drugs — metoclopramide;Hand-feeding hay to stimulate gut movement.",
        "prevention": "Feed unlimited hay as 80% of diet;Ensure constant access to fresh water;Minimize stress;Provide daily exercise;Regular veterinary check-ups to identify dental or pain issues early."
    },
    "Giardiasis": {
        "description": "A protozoal infection of the small intestine caused by Giardia duodenalis, causing soft, greasy, malodorous diarrhea in dogs, cats, and other mammals. Zoonotic — can spread to humans.",
        "treatment": "Fenbendazole for 5 days;Metronidazole for 5-7 days;Combination of both is more effective;Bathe the animal to remove cysts from fur;Disinfect environment — use quaternary ammonium compounds.",
        "prevention": "Prevent drinking from puddles, ponds, or streams;Use filtered or tap water;Avoid contact with infected animals' feces;Wash hands after handling animals;Clean and disinfect water bowls regularly."
    },
    "Heartworm Disease": {
        "description": "Dirofilariasis — a life-threatening condition caused by Dirofilaria immitis worms living in the heart and pulmonary arteries, transmitted by mosquitoes. Dogs are the primary host. Cats and ferrets are atypical hosts with sudden death as a risk.",
        "treatment": "Dogs: Melarsomine injections (3 doses over 4 weeks) with strict cage rest;Pre-treat with doxycycline and monthly preventive;Dogs must be confined during and after treatment to prevent pulmonary embolism;Cats: No approved drug treatment — supportive care only.",
        "prevention": "Year-round monthly preventive — ivermectin, milbemycin, or moxidectin;Annual heartworm blood test;Mosquito control;Do not skip prevention — even a single missed month creates risk."
    },
    "Hyperthyroidism": {
        "description": "The most common hormonal disease in cats, caused by overproduction of thyroid hormones from a benign thyroid tumor. Causes weight loss despite increased appetite, hyperactivity, vomiting, and increased drinking/urination. Rare in dogs.",
        "treatment": "Daily oral medication — methimazole (Felimazole);Radioactive iodine therapy (I-131) — most effective, curative;Surgical removal of the thyroid gland;Prescription iodine-restricted diet (Hills y/d).",
        "prevention": "No prevention — annual blood testing for cats over 8 years;Regular vet checks to catch early-stage disease;Early diagnosis and treatment prevents secondary heart and kidney disease."
    },
    "Inflammatory Bowel Disease": {
        "description": "IBD is a chronic inflammatory condition of the GI tract in dogs and cats caused by infiltration of inflammatory cells into the gut wall. Causes chronic vomiting, diarrhea, and weight loss. Distinct from irritable bowel syndrome.",
        "treatment": "Immunosuppressive drugs — prednisolone, budesonide;Novel protein diet or hydrolyzed protein diet;Vitamin B12 supplementation;Antibiotics — metronidazole;Probiotics;Rule out food allergy with diet trial.",
        "prevention": "Feed a consistent, high-quality diet;Avoid dietary indiscretion;Regular vet check-ups;Early investigation of chronic vomiting or diarrhea before disease progresses."
    },
    "Intestinal Parasites": {
        "description": "A range of parasitic worms and protozoa (roundworms, hookworms, tapeworms, whipworms, Giardia, Coccidia) infecting the intestinal tract of animals, causing diarrhea, weight loss, anemia, and failure to thrive.",
        "treatment": "Anthelmintic drugs appropriate to parasite species;Pyrantel pamoate for roundworms and hookworms;Praziquantel for tapeworms;Fenbendazole for broad-spectrum coverage;Metronidazole or fenbendazole for Giardia.",
        "prevention": "Regular deworming every 3 months (monthly for puppies);Fecal examination at annual check-ups;Prevent eating of feces, rodents, and raw meat;Good hygiene — pick up feces promptly;Flea control to break tapeworm cycle."
    },
    "Johne's Disease": {
        "description": "Paratuberculosis caused by Mycobacterium avium paratuberculosis (MAP). A chronic, progressive wasting disease of ruminants causing profuse diarrhea, bottle jaw (submandibular edema), and eventual death. Long incubation — 2-10 years.",
        "treatment": "No effective cure;Cull clinical animals;ELISA and fecal culture testing to identify and cull infected animals;Supportive care to maintain quality of life briefly.",
        "prevention": "Test-and-cull protocols;Separate calves/kids/lambs from infected adults immediately;Source replacements from tested clean herds;Strict biosecurity in calving and lambing areas;Vaccine available in some countries for damage limitation."
    },
    "Lameness": {
        "description": "Lameness in animals is not a disease itself but a clinical sign of pain or mechanical dysfunction in one or more limbs. Caused by injury, arthritis, laminitis, infections, foreign bodies in the foot, or nerve damage.",
        "treatment": "Identify and treat the underlying cause;NSAIDs for pain and inflammation;Rest and restricted movement;Hoof trimming and foot bathing for hoof conditions;Physiotherapy during recovery.",
        "prevention": "Maintain healthy body weight;Provide appropriate flooring — avoid slippery or hard surfaces;Hoof care and trimming on regular schedule;Prompt investigation of any new lameness — early treatment prevents chronicity."
    },
    "Laminitis": {
        "description": "Inflammation of the sensitive laminae within the hoof in horses, ponies, donkeys, and rarely cattle and goats. Causes extreme pain, characteristic leaning-back stance, and in severe cases, rotation of the pedal bone through the sole.",
        "treatment": "Emergency removal from grass immediately;Deep sand or shavings bedding for support;Frog support pads;NSAIDs — phenylbutazone;Treat the primary cause (grain overload, infection, Cushing's);X-rays to check for rotation.",
        "prevention": "Gradual introduction to lush spring pasture;Restrict high-risk ponies and horses to dry lots;Low-sugar, low-starch diet;Treat underlying hormonal conditions;Maintain healthy weight;Regular shoeing and hoof care."
    },
    "Maedi Visna": {
        "description": "A slow, progressive lentiviral disease of sheep (and occasionally goats) causing chronic pneumonia (maedi) and neurological disease (visna). Transmitted through colostrum, milk, and respiratory secretions. Incubation period is years.",
        "treatment": "No treatment or cure available;Cull clinically affected animals;Management in flock to reduce losses.",
        "prevention": "Test-and-cull using AGID or ELISA blood tests;Rear lambs away from infected ewes;Feed heat-treated colostrum;Source replacement sheep from accredited MV-free flocks."
    },
    "Myxomatosis": {
        "description": "A severe viral disease of European rabbits (Oryctolagus cuniculus) caused by Myxoma virus, transmitted by biting insects. Causes puffy, swollen face, blindness, and pneumonia, with near 100% mortality in unvaccinated wild-type European rabbits.",
        "treatment": "Supportive care — fluids, nutrition, nursing;Antibiotics for secondary bacterial infections;Analgesics for pain management;Prognosis is very poor for unvaccinated rabbits;Vaccinated rabbits may recover with intensive care.",
        "prevention": "Vaccination — single annual dose provides excellent protection;Insect control — use fly screens and insect-repellent collars;Avoid rabbit contact with areas where wild rabbits are present."
    },
    "Pancreatitis": {
        "description": "Inflammation of the pancreas causing pain, vomiting, and diarrhea in dogs and cats. Acute pancreatitis can be mild or life-threatening. Common triggers include fatty meals in dogs and stress or IBD in cats.",
        "treatment": "Nil by mouth initially — then introduce bland diet gradually;IV fluid therapy;Pain management — buprenorphine or methadone;Anti-nausea drugs;Plasma transfusion in severe cases;Long-term low-fat diet management.",
        "prevention": "Feed a low-fat diet consistently;Never give fatty table scraps to dogs;Manage body weight;Treat underlying hormonal diseases (hypothyroidism, diabetes) that increase risk;Regular blood tests in at-risk breeds (Miniature Schnauzers, Cocker Spaniels)."
    },
    "Panleukopenia": {
        "description": "Feline Panleukopenia — also called feline distemper — is a highly contagious and often fatal viral disease caused by Feline Parvovirus. Causes severe enteritis, bone marrow suppression, and high mortality in unvaccinated kittens.",
        "treatment": "Intensive hospitalization;IV fluids and electrolytes;Antibiotics for secondary infections;Anti-nausea drugs;Blood or plasma transfusions;Interferon-omega in some protocols.",
        "prevention": "Core vaccination — FVRCP — is the primary prevention;Complete the kitten series;Annual or triennial boosters;Disinfect with bleach;Isolate infected cats."
    },
    "Parasites": {
        "description": "A broad category of organisms living at the expense of the host animal, including ectoparasites (fleas, ticks, mites, lice) and endoparasites (worms, protozoa). Cause skin irritation, anemia, malnutrition, and serve as vectors for diseases.",
        "treatment": "Species-specific antiparasitic treatment;Anthelmintics for internal worms;Ectoparasiticides (spot-ons, collars, sprays) for external parasites;Treat the animal AND the environment;Retest feces 2-4 weeks after treatment.",
        "prevention": "Year-round flea and tick prevention;Regular deworming program;Annual fecal egg counts;Prevent access to feces, carrion, and raw meat;Regular grooming and physical examination."
    },
    "Parvovirus": {
        "description": "Canine Parvovirus (CPV-2) is one of the most serious and contagious dog diseases. It attacks the intestinal tract and immune system causing profuse bloody diarrhea, vomiting, severe dehydration, and sepsis. Highly fatal without intensive treatment.",
        "treatment": "Hospitalization with intensive IV fluid and electrolyte therapy;Antibiotics to prevent septicemia;Antiemetics — maropitant (Cerenia);Nutritional support — nasogastric feeding if needed;Blood or plasma transfusion in severe cases.",
        "prevention": "Vaccination is the most effective prevention — complete the puppy series;Annual boosters;Avoid contact with unvaccinated dogs;The virus is stable in the environment for 6-12 months — disinfect with sodium hypochlorite."
    },
    "Pasteurellosis": {
        "description": "Bacterial infection caused by Pasteurella multocida, affecting rabbits (snuffles), poultry, cattle, and other animals. In rabbits, causes nasal discharge, head tilt, and abscesses. In cattle, contributes to pneumonia and septicemia.",
        "treatment": "Enrofloxacin or trimethoprim-sulfamethoxazole antibiotics;Long treatment courses are required (4-6 weeks for rabbits);Surgical drainage of abscesses;Supportive care.",
        "prevention": "Vaccination available for some species;Reduce stress — a major trigger in rabbits;Source animals from Pasteurella-free herds/breeders;Maintain good ventilation;Quarantine new animals."
    },
    "Pneumonia": {
        "description": "Inflammation and infection of the lungs from bacteria, viruses, fungi, or aspiration of material. Causes respiratory distress, fever, coughing, and can be fatal. Common in cattle, horses, dogs, and cats, particularly young or stressed animals.",
        "treatment": "Antibiotics appropriate to causative organism;Anti-inflammatory NSAIDs for fever;Bronchodilators to open airways;IV fluids if severely ill;Nursing care — keep warm and well-nourished.",
        "prevention": "Vaccination against common respiratory pathogens;Reduce stress — especially during weaning and transport;Maintain good ventilation;Ensure adequate colostrum intake in young animals;Prompt treatment of early respiratory signs."
    },
    "Porcine Circovirus Disease": {
        "description": "Post-weaning Multisystemic Wasting Syndrome (PMWS) caused by Porcine Circovirus 2 (PCV2). Causes severe immune suppression, wasting, and high mortality in weaned pigs. A major economic disease of global pig production.",
        "treatment": "No specific treatment;Supportive care for affected pigs;Remove severely affected pigs;Anti-inflammatory and antibiotic treatment for secondary conditions;Vaccine reduces disease severity.",
        "prevention": "Vaccination with PCV2 vaccines (highly effective);Good colostrum management;Reduce stress;All-in all-out production systems;Control concurrent PRRS infection."
    },
    "Porcine Epidemic Diarrhea": {
        "description": "PED is caused by Porcine Epidemic Diarrhea Virus (PEDV) and causes watery diarrhea with near 100% mortality in suckling pigs under 1 week of age. Older pigs survive but production losses are severe. Spreads rapidly.",
        "treatment": "Supportive care — electrolytes and warmth;Maintain hydration in affected pigs;Nurse-sow programs to allow passive immunity transfer;No specific antiviral treatment.",
        "prevention": "Vaccination of sows to pass immunity to piglets;Strict biosecurity — PEDV spreads readily on equipment and clothing;Biosecure transport of pigs;Controlled exposure of sow herds (feedback) to generate immunity before farrowing."
    },
    "Porcine Reproductive and Respiratory Syndrome": {
        "description": "PRRS — also called blue ear disease — is one of the most economically significant swine diseases worldwide. Caused by PRRSV, it causes reproductive failure (late abortions, mummified piglets) and respiratory disease in pigs of all ages.",
        "treatment": "No specific treatment;Antibiotics for secondary bacterial infections;Supportive care — fluids, warmth, good nutrition;Strategic use of autogenous vaccines.",
        "prevention": "Vaccination with modified live or killed PRRS vaccines;Strict air filtration biosecurity for PRRS-negative herds;Closed herd management;Source pigs from PRRS-negative herds;Acclimatization programs for replacement gilts."
    },
    "Porcine Respiratory Disease Complex": {
        "description": "A multifactorial respiratory disease of pigs involving multiple viruses (PRRSV, SIV, PCV2) and bacteria (Mycoplasma hyopneumoniae, Pasteurella multocida) acting together. Causes coughing, fever, growth retardation, and deaths in finisher pigs.",
        "treatment": "Antibiotics for bacterial components;Anti-inflammatories for fever;Improve environmental conditions;Vaccination against major pathogens.",
        "prevention": "Implement comprehensive vaccination program;All-in all-out production systems;Good ventilation and stocking density;Minimize mixing of pigs from different sources."
    },
    "Pregnancy": {
        "description": "Normal pregnancy — the animal is pregnant and displaying typical signs of gestation such as weight gain, mammary development, behavioral changes, and nesting behavior. This is NOT a disease.",
        "treatment": "Provide high-quality, nutrition-dense diet;Regular monitoring — ideally with ultrasound;Ensure clean, quiet, comfortable birthing area is available;Prepare for parturition with appropriate veterinary support.",
        "prevention": "Pregnancy is a natural physiological process. To prevent unwanted pregnancies: spay or neuter;Use controlled breeding programs;Monitor heat cycles closely."
    },
    "Rabbit Calicivirus": {
        "description": "Rabbit Hemorrhagic Disease Virus (RHDV/RHDV2) causes rapidly fatal viral hemorrhagic disease in European rabbits. Often causing sudden death with bleeding from nose and mouth. RHDV2 affects even young kittens.",
        "treatment": "No effective treatment — death is often sudden;Supportive care (fluids, warmth) in the very rare survivor;Quarantine all in-contact rabbits.",
        "prevention": "Vaccination — RHDV2 vaccine annually;Keep house rabbits from contact with wild rabbits, insects, and contaminated material;Insect screening to prevent vector transmission."
    },
    "Rabbit Hemorrhagic Disease": {
        "description": "Viral Hemorrhagic Disease (VHD) is a highly contagious and often fatal disease of European rabbits caused by Rabbit Calicivirus (RHDV and RHDV2). Spreads through direct contact and fomites. Causes internal bleeding and rapid death.",
        "treatment": "Supportive care only;No specific antiviral treatment;Isolate all affected and in-contact rabbits.",
        "prevention": "Annual RHDV2 vaccination;Prevent contact with wild rabbits and fomites;Control insects;Clean and disinfect equipment."
    },
    "Rabbit Syphilis": {
        "description": "Caused by Treponema paraluiscuniculi, this bacterial venereal disease of rabbits causes ulcers and crusting around the nose, lips, genitals, and eyelids. Does NOT transmit to humans or other species.",
        "treatment": "Penicillin G injections for 3 weeks — highly effective;Treat all breeding rabbits in the group;Clean lesions with antiseptic.",
        "prevention": "Examine rabbits before breeding;Do not breed from affected animals;Quarantine new rabbits before introduction to breeding groups."
    },
    "Respiratory Infection": {
        "description": "Infections of the upper or lower respiratory tract caused by bacteria, viruses, or fungi. Common in all pet species, causing coughing, nasal discharge, and respiratory distress. Severity ranges from mild to pneumonia.",
        "treatment": "Antibiotics for bacterial infections;Antivirals for specific viral diseases;Supportive care — rest, fluids, nutrition;Nebulization for lower respiratory disease;Antifungals for fungal pneumonia.",
        "prevention": "Vaccination against common respiratory pathogens;Quarantine new animals;Avoid overcrowding and poor ventilation;Minimize stress;Prompt treatment of mild symptoms before progression."
    },
    "Respiratory Syncytial Virus": {
        "description": "RSV is a major cause of lower respiratory tract disease in young cattle (BRSV) and occasionally other species. Causes bronchiolitis and interstitial pneumonia, often concurrent with other BRD pathogens.",
        "treatment": "Anti-inflammatory NSAIDs;Antibiotics for secondary bacterial infections;Bronchodilators may provide symptomatic relief;Supportive nursing care.",
        "prevention": "Vaccination with BRSV-containing respiratory vaccines;Minimize mixing of age groups;Improve ventilation in housing;Ensure adequate colostrum in young calves."
    },
    "Salmonellosis": {
        "description": "Bacterial infection caused by Salmonella species, causing acute diarrhea, fever, and septicemia in animals and humans. Zoonotic — all species including humans are at risk. Animals can be asymptomatic carriers. Poultry are a major reservoir.",
        "treatment": "Rehydration therapy;Antibiotics — fluoroquinolones or trimethoprim-sulfamethoxazole;Isolate infected animals;Supportive care;Note: antibiotics in subclinical carriers are controversial and may prolong shedding.",
        "prevention": "Strict hygiene — wash hands after handling animals;Avoid feeding raw meat;Control rodents;Good hygiene in food and water supplies;Reduce stress in animals;Vaccination available for cattle in some countries."
    },
    "Scrapie": {
        "description": "A fatal prion disease of sheep and goats causing progressive neurological signs — itching, incoordination, and behavioral changes. Part of the transmissible spongiform encephalopathy (TSE) family including BSE in cattle.",
        "treatment": "No treatment or cure available;Euthanize confirmed cases;Report to authorities immediately — notifiable disease.",
        "prevention": "Select breeding sheep with scrapie-resistant PrP genotypes (ARR/ARR);Test breeding rams;Monitor flocks carefully for neurological signs;Import replacement animals from clean flocks."
    },
    "Skin Lesions": {
        "description": "A broad category of skin abnormalities including papules, nodules, ulcers, pustules, and plaques caused by infections (bacteria, fungi, viruses), parasites, allergies, immune conditions, or neoplasia. Requires diagnosis to guide treatment.",
        "treatment": "Identify and treat the underlying cause;Bacterial: topical chlorhexidine and systemic antibiotics;Fungal: antifungals;Parasitic: appropriate antiparasitic;Allergic: allergen avoidance, antihistamines, steroids.",
        "prevention": "Regular grooming and skin examination;Parasite prevention;Feed a high-quality, balanced diet supporting skin health;Prompt investigation and treatment of any new skin lesion."
    },
    "Snuffles": {
        "description": "Pasteurellosis in rabbits — caused by Pasteurella multocida. Causes chronic upper respiratory infection with thick nasal discharge, sneezing, and conjunctivitis. Can progress to middle ear infection, head tilt, and abscesses.",
        "treatment": "Long-course antibiotics — enrofloxacin or trimethoprim-sulfamethoxazole for 4-6 weeks;Nebulization with saline or antibiotic solutions;Supportive care — ensure eating and drinking;Surgical drainage of abscesses.",
        "prevention": "Source rabbits from Pasteurella-free breeders;Reduce stress — primary trigger of disease;Good ventilation in housing;Avoid drafts;Annual veterinary check-ups."
    },
    "Strangles": {
        "description": "A highly contagious bacterial disease of horses caused by Streptococcus equi equi. Causes fever, thick nasal discharge, and abscess formation in the lymph nodes of the head and neck. Spreads rapidly at equine facilities.",
        "treatment": "Rest and supportive care;Hot packing of lymph node abscesses to encourage rupture;Antibiotics — penicillin for systemic cases or prevention of bastard strangles;Drain mature abscesses;Isolate for 6-8 weeks after recovery.",
        "prevention": "Vaccination with IntraTect or Equilis Strep E;Strict biosecurity at shows and competitions;Isolate new horses for 3 weeks;Isolate any horse with nasal discharge;Disinfect shared equipment."
    },
    "Swine Dysentery": {
        "description": "A severe mucohaemorrhagic diarrheal disease of pigs caused by Brachyspira hyodysenteriae. Causes profuse watery-to-bloody diarrhea in growing pigs, significant production losses, and is difficult to eradicate once established.",
        "treatment": "Antibiotics — tiamulin, lincomycin, or valnemulin in feed or water;Medical treatment suppresses disease but does not eradicate;All-in all-out and strict biosecurity to eliminate.",
        "prevention": "Prevent introduction through rigorous biosecurity;Source pigs from Swine Dysentery-free herds;Rodent control — rodents are a major reservoir;All-in all-out production systems;No licensed vaccine — prevention through management."
    },
    "Swine Erysipelas": {
        "description": "Caused by Erysipelothrix rhusiopathiae, this bacterial disease of pigs causes three syndromes: acute septicemia with characteristic diamond-skin lesions, subacute urticaria, and chronic arthritis or endocarditis. Zoonotic to humans.",
        "treatment": "High-dose penicillin — highly effective if given early;NSAIDs for fever;Supportive care;Vaccination is the primary control tool.",
        "prevention": "Vaccination — swine erysipelas vaccine given twice yearly;Reduce stress;Good hygiene;Handle affected animals with gloves as zoonotic risk to humans."
    },
    "Swine Fever": {
        "description": "Classical Swine Fever (CSF) — also called hog cholera — is caused by a pestivirus and is an OIE-notifiable disease causing severe immunosuppression, hemorrhage, and high mortality. Eradicated in many countries but still endemic in parts of Asia, Africa, and Latin America.",
        "treatment": "No treatment in most countries with eradication programs — mandatory slaughter;Supportive care in endemic areas;Vaccination in endemic countries.",
        "prevention": "Vaccination in endemic countries;Strict import controls;Biosecurity — do not feed kitchen waste or swill to pigs;Immediately report suspected cases to authorities."
    },
    "Swine Flu": {
        "description": "Swine Influenza (SIV) — caused by influenza A viruses (H1N1, H1N2, H3N2) — causes acute respiratory disease in pigs with coughing, nasal discharge, and fever. Some strains have pandemic potential in humans (2009 H1N1 pandemic).",
        "treatment": "Supportive care — rest, fluids, good nutrition;Anti-inflammatory drugs for fever;Antibiotics for secondary bacterial pneumonia;Affected pigs usually recover within 1 week.",
        "prevention": "Vaccination with polyvalent SIV vaccines;Biosecurity at pig shows and markets;Zoonotic risk — people with flu should avoid close contact with pigs."
    },
    "Swine Influenza": {
        "description": "SIV is a respiratory disease of pigs causing high morbidity but low mortality in healthy adult pigs. Young piglets and immunocompromised animals are most at risk. Can reassort with human influenza viruses creating pandemic strains.",
        "treatment": "Supportive care;Anti-inflammatories;Antibiotics for secondary bacterial pneumonia;Affected herds typically recover within 2 weeks.",
        "prevention": "Vaccination;Biosecurity;Minimize pig-human interface during outbreaks;Surveillance and rapid reporting."
    },
    "Tick Borne Disease": {
        "description": "A range of diseases transmitted by ticks including Lyme disease (Borrelia), Anaplasmosis, Ehrlichiosis, Babesiosis, and Rocky Mountain Spotted Fever. Cause fever, lethargy, joint pain, and organ damage across multiple species.",
        "treatment": "Doxycycline for most bacterial tick-borne diseases;Imidocarb for Babesia/Theileria;Tick removal — use proper technique with tick remover;Supportive care for organ support.",
        "prevention": "Year-round tick prevention products (spot-ons, collars, chewables);Check animals thoroughly after time outdoors;Vaccination for Lyme disease in dogs (in endemic areas);Keep grass short;Avoid walking in tick-infested areas during peak season."
    },
    "Tuberculosis": {
        "description": "Bovine Tuberculosis (bTB) caused by Mycobacterium bovis infects cattle and many other mammals including badgers, deer, and humans. Causes chronic wasting, respiratory disease, and enlarged lymph nodes. A major zoonotic public health concern.",
        "treatment": "No treatment in most countries — mandatory slaughter of positive reactors;Compensation paid to farmers in national eradication programs.",
        "prevention": "Routine tuberculin skin testing;Slaughter-and-compensate programs;Badger culling and vaccination in endemic areas;BCG vaccination trials underway for cattle;Strict movement controls on tested herds."
    },
    "Upper Respiratory Infection": {
        "description": "Common viral or bacterial infection of the nose, throat, and sinuses in dogs, cats, and rabbits. Symptoms include sneezing, nasal discharge, eye discharge, and lethargy. Usually self-limiting in healthy adults but severe in kittens and puppies.",
        "treatment": "Supportive care — rest, warmth, hydration;Antibiotics for secondary bacterial infection;Nebulization with saline for nasal congestion;Appetite stimulants and syringe feeding if anorexic;L-lysine for herpesvirus-related disease in cats.",
        "prevention": "Vaccination — FVRCP for cats, DHPP for dogs;Quarantine new animals;Good ventilation and hygiene in multi-animal households;Reduce stress;Prompt treatment of early symptoms."
    },
    "West Nile Virus": {
        "description": "West Nile Virus is transmitted by Culex mosquitoes and can infect horses, birds, and occasionally humans. In horses, it causes neurological signs including encephalitis, ataxia, and weakness. Mortality is significant in clinical cases.",
        "treatment": "Supportive care only — no specific antiviral;Anti-inflammatory drugs for brain inflammation;Intensive nursing for recumbent horses;Physical therapy during recovery.",
        "prevention": "Vaccination — highly effective WNV vaccines for horses;Mosquito control — eliminate standing water;Stable horses during peak mosquito hours (dusk to dawn);Annual boosters."
    },
    "Equine West Nile Virus": {
        "description": "West Nile Virus in horses causes encephalitis and myelitis via Culex mosquito transmission. Clinical signs include muscle fasciculations, ataxia, difficulty swallowing, and death in severe cases. Mortality approaches 30% in clinical cases.",
        "treatment": "Supportive care — IV fluids, NSAIDs;Anti-seizure medication if needed;Intensive nursing for recumbent horses;Slinging to prevent decubitus ulcers.",
        "prevention": "Biannual WNV vaccination in endemic areas;Mosquito control;Stable horses at dusk and dawn;Insect repellents."
    },
    "Feline Coronavirus": {
        "description": "FCoV is prevalent in multi-cat households and causes asymptomatic infection or mild enteritis in most cats. In a small fraction, the virus mutates causing the life-threatening Feline Infectious Peritonitis (FIP).",
        "treatment": "Most FCoV infections need no treatment;For FIP: GS-441524 antiviral (highly effective);Supportive care for FIP including draining effusions.",
        "prevention": "Reduce cat density and stress;Separate litter trays per cat;Quarantine new cats;Early FIP detection improves treatment outcomes."
    },
    "Bovine Influenza": {
        "description": "Bovine Influenza contributes to the Bovine Respiratory Disease Complex. Caused by influenza D virus and bovine parainfluenza virus, leading to fever, nasal discharge, coughing, and predisposing to secondary bacterial pneumonia.",
        "treatment": "Anti-inflammatory NSAIDs;Antibiotics for secondary bacterial infections;Supportive care;Rest.",
        "prevention": "Vaccination against respiratory pathogens;Reduce overcrowding;Ensure good ventilation;Minimize transport stress."
    },
}


# ── Helper functions ──────────────────────────────────────────────────────────

def get_urgency(disease_name: str) -> str:
    name_lower = disease_name.lower()
    if any(c in name_lower for c in ["parvovirus", "rabies", "bloat", "anthrax", "foot and mouth", "african swine", "haemorrhagic", "septicaemia", "fever (haemorrhagic)"]):
        return "Emergency"
    if any(m in name_lower for m in ["healthy", "pregnancy"]):
        return "Monitor"
    return "Schedule Vet Visit"


def lookup_disease_info(name: str) -> dict:
    """Multi-layer disease info lookup: direct match -> alias map -> inline info -> fallback."""
    # Layer 1: direct key match in disease_info.json
    if name in disease_info:
        info = disease_info[name]
        if info.get("description", "") not in ("Clinical medical condition.", ""):
            return info

    # Layer 2: alias map -> disease_info.json
    alias = DISEASE_ALIAS.get(name)
    if alias and alias in disease_info:
        info = disease_info[alias]
        if info.get("description", "") not in ("Clinical medical condition.", ""):
            return info

    # Layer 3: inline curated info
    if name in INLINE_INFO:
        return INLINE_INFO[name]

    # Layer 4: fallback
    urg = get_urgency(name)
    return {
        "description": f"{name} is a recognized veterinary condition requiring professional evaluation.",
        "treatment": "Seek emergency veterinary care immediately. Do not delay." if urg == "Emergency"
                     else "Consult a veterinarian for a full diagnosis and tailored treatment plan.",
        "prevention": "Maintain regular veterinary check-ups, follow vaccination schedules, and practice good animal husbandry."
    }


def validate_vitals(animal_type: str, temperature: Optional[float], heart_rate: Optional[float]) -> Optional[str]:
    """
    Returns an error message string if vitals are unrealistically out of range,
    or None if they are acceptable.
    """
    if temperature is not None:
        if temperature < TEMP_ABSOLUTE_MIN or temperature > TEMP_ABSOLUTE_MAX:
            return (
                f"Temperature {temperature}°C is outside the biologically possible range "
                f"({TEMP_ABSOLUTE_MIN}–{TEMP_ABSOLUTE_MAX}°C). Please re-check and enter a valid reading."
            )
        normal = VITALS_RANGES.get(animal_type, {}).get("temp")
        if normal:
            lo, hi = normal
            # Allow 3°C outside normal range before flagging as unrealistic
            if temperature < (lo - 3) or temperature > (hi + 3):
                return (
                    f"Temperature {temperature}°C is far outside the normal range for {animal_type} "
                    f"({lo}–{hi}°C). Please verify your reading — this value appears unrealistic."
                )

    if heart_rate is not None:
        if heart_rate < HR_ABSOLUTE_MIN or heart_rate > HR_ABSOLUTE_MAX:
            return (
                f"Heart rate {heart_rate} bpm is outside the biologically possible range "
                f"({HR_ABSOLUTE_MIN}–{HR_ABSOLUTE_MAX} bpm). Please re-check your measurement."
            )
        normal = VITALS_RANGES.get(animal_type, {}).get("hr")
        if normal:
            lo, hi = normal
            # Allow 3x outside normal range before flagging as unrealistic
            margin_lo = max(lo - 40, HR_ABSOLUTE_MIN)
            margin_hi = hi + 100
            if heart_rate < margin_lo or heart_rate > margin_hi:
                return (
                    f"Heart rate {int(heart_rate)} bpm is far outside the normal range for {animal_type} "
                    f"({lo}–{hi} bpm). Please verify your reading — this value appears unrealistic."
                )
    return None


# ── Pydantic Models ──────────────────────────────────────────────────────────

class TextRequest(BaseModel):
    text: str

class PredictRequest(BaseModel):
    animal_type: str
    symptoms: List[str]
    temperature: Optional[float] = None
    heart_rate: Optional[float] = None

class PredictResult(BaseModel):
    disease: str
    confidence: float
    urgency: str
    description: str
    treatment: str
    prevention: str


# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/")
def health_check():
    return {
        "status": "ok",
        "version": "5.0.0",
        "nlp_engine": "HuggingFace all-MiniLM-L6-v2 (semantic)",
        "symptoms": len(master_symptoms),
        "embedding_phrases": len(_sym_labels),
        "hf_token_present": bool(_HF_TOKEN),
    }


async def _fetch_hf_embedding(text: str) -> Optional[np.ndarray]:
    """
    Calls the HF free inference API to get a 384-dim embedding for `text`.
    Returns None if the token is missing, the API is unavailable, or any
    error occurs — allowing graceful fallback to layers 1+2 only.
    """
    if not _HF_TOKEN:
        return None
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(
                _HF_URL,
                headers=_HF_HEADERS,
                json={"inputs": text},
            )
        if resp.status_code != 200:
            return None
        data = resp.json()
        # API can return [vec] or [[vec]] — normalise both
        if isinstance(data[0], list):
            vec = data[0]
        else:
            vec = data
        return np.array(vec, dtype=np.float32).reshape(1, -1)
    except Exception:
        return None


async def _extract_symptoms_logic(req: TextRequest):
    """
    Three-layer symptom extraction pipeline:

    Layer 1 — Direct substring match (zero latency, no API)
        Catches obvious exact or near-exact mentions in the text.

    Layer 2 — Synonym regex rules (zero latency, no API)
        Catches natural synonyms: 'limping' → Lameness, 'won't eat' → Appetite Loss.

    Layer 3 — HF semantic embedding + cosine similarity (async, only when needed)
        Embeds the user's full sentence with all-MiniLM-L6-v2 and compares
        against pre-calculated phrase vectors for every canonical symptom.
        Only invoked when layers 1+2 found fewer than 2 symptoms.
        Gracefully skipped if HF_TOKEN is not set or the API is unavailable.
    """
    if not req.text.strip():
        return {"matched_symptoms": []}

    user_query = req.text.lower().strip()
    detected: list[str] = []

    # ── Layer 1: Direct substring check ──────────────────────────────────────
    for sym in master_symptoms:
        if sym.lower() in user_query and sym not in detected:
            detected.append(sym)

    # ── Layer 2: Synonym / regex rules ───────────────────────────────────────
    for sym, keywords in SYNONYM_RULES.items():
        if sym in _master_sym_set and sym not in detected:
            for kw in keywords:
                if re.search(r'\b' + re.escape(kw) + r'\b', user_query):
                    detected.append(sym)
                    break

    # ── Layer 3: Semantic embedding fallback (HF API) ─────────────────────────
    # Only call the HF API when the fast layers didn't catch enough symptoms.
    # This keeps latency low for simple, obvious inputs.
    if len(detected) < 2:
        user_vec = await _fetch_hf_embedding(user_query)
        if user_vec is not None:
            sims = cosine_similarity(user_vec, _sym_embeddings)[0]  # shape (N,)

            # Walk from highest similarity downward — keep track of (label, score)
            top_indices = np.argsort(sims)[::-1]
            sem_candidates: list[tuple[str, float]] = []
            for idx in top_indices:
                if sims[idx] < _SEM_THRESHOLD:
                    break
                candidate = _sym_labels[idx]
                if candidate in _master_sym_set and candidate not in detected:
                    if not any(x[0] == candidate for x in sem_candidates):
                        sem_candidates.append((candidate, float(sims[idx])))

            # Apply mutual exclusion: Appetite Loss vs Increased Appetite
            if "Appetite Loss" in detected:
                sem_candidates = [x for x in sem_candidates if x[0] != "Increased Appetite"]
            if "Increased Appetite" in detected:
                sem_candidates = [x for x in sem_candidates if x[0] != "Appetite Loss"]

            app_loss_score = next((x[1] for x in sem_candidates if x[0] == "Appetite Loss"), None)
            inc_app_score  = next((x[1] for x in sem_candidates if x[0] == "Increased Appetite"), None)
            if app_loss_score is not None and inc_app_score is not None:
                if app_loss_score >= inc_app_score:
                    sem_candidates = [x for x in sem_candidates if x[0] != "Increased Appetite"]
                else:
                    sem_candidates = [x for x in sem_candidates if x[0] != "Appetite Loss"]

            # Add up to 8 unique symptoms
            for candidate, score in sem_candidates:
                detected.append(candidate)
                if len(detected) >= 8:
                    break

    return {"matched_symptoms": detected}


@app.post("/extract-symptoms")
async def extract_symptoms_hyphen(req: TextRequest):
    """Translates free text to matching symptom checkboxes (hyphen path)."""
    return await _extract_symptoms_logic(req)


@app.post("/extract_symptoms")
async def extract_symptoms_underscore(req: TextRequest):
    """Translates free text to matching symptom checkboxes (underscore alias)."""
    return await _extract_symptoms_logic(req)


@app.post("/predict", response_model=List[PredictResult])
def predict(req: PredictRequest):
    try:
        species_list = encoders["species"]
        if req.animal_type not in species_list:
            raise HTTPException(
                status_code=400,
                detail=f"Species '{req.animal_type}' is not supported. Supported: {species_list}"
            )

        # ── Vitals validation ──────────────────────────────────────────────────
        vitals_error = validate_vitals(req.animal_type, req.temperature, req.heart_rate)
        if vitals_error:
            raise HTTPException(status_code=422, detail=vitals_error)

        sp_enc = species_list.index(req.animal_type)
        species_vitals = encoders.get("healthy_vitals", {}).get(req.animal_type, {"temp": 38.5, "hr": 85.0})
        temp = req.temperature if req.temperature is not None else species_vitals["temp"]
        hr   = req.heart_rate  if req.heart_rate  is not None else species_vitals["hr"]

        sym_list = encoders["symptoms"]
        sym_vec  = [1 if s in req.symptoms else 0 for s in sym_list]

        features = pd.DataFrame(
            [[sp_enc, temp, hr] + sym_vec],
            columns=encoders["feature_names"],
        )

        probs = model.predict_proba(features)[0]

        disease_list = encoders["disease"]

        # ── Guard 1: Pregnancy — suppress when no pregnancy indicators present ──
        pregnancy_indicators = {
            "Nesting Behavior", "Clear Vaginal Discharge",
            "Bloody Vaginal Discharge", "Purulent Vaginal Discharge",
            "Fetal Heart Sound Detected", "Increased Appetite",
        }
        has_pregnancy_indicator = any(s in req.symptoms for s in pregnancy_indicators)
        if not has_pregnancy_indicator:
            try:
                preg_idx = disease_list.index("Pregnancy")
                probs[preg_idx] = 0.0
            except ValueError:
                pass

        # ── Guard 2: Healthy — suppress when animal has symptoms or abnormal vitals
        # A sick animal should never be predicted as healthy.
        has_symptoms     = len(req.symptoms) > 0
        vitals_abnormal  = _vitals_are_abnormal(req.animal_type, req.temperature, req.heart_rate)
        if has_symptoms or vitals_abnormal:
            try:
                healthy_idx = disease_list.index("Healthy / No Disease")
                probs[healthy_idx] = 0.0
            except ValueError:
                pass

        # ── Guard 3: Species-disease filter — zero out biologically impossible diseases
        # e.g., Bovine Tuberculosis for a Cat, Feline Herpesvirus for a Horse.
        for idx, dis_name in enumerate(disease_list):
            if not _is_disease_allowed_for_species(dis_name, req.animal_type):
                probs[idx] = 0.0

        # Re-normalise after all suppressions
        total = probs.sum()
        if total > 0:
            probs = probs / total

        top3 = np.argsort(probs)[::-1][:3]

        results = []
        for idx in top3:
            conf = round(float(probs[idx]) * 100, 1)
            if conf < 5.0:
                continue
            name = encoders["disease"][idx]
            info = lookup_disease_info(name)
            urg  = get_urgency(name)

            results.append(
                PredictResult(
                    disease=name,
                    confidence=conf,
                    urgency=urg,
                    description=info.get("description", ""),
                    treatment=info.get("treatment", ""),
                    prevention=info.get("prevention", ""),
                )
            )
        return results

    except HTTPException as he:
        raise he
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))